# Deployment conversao-peso
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-peso
spec:
  selector:
    matchLabels:
      app: conversao-peso
  template:
    metadata:
      labels:
        app: conversao-peso
    spec:
      containers:
      - name: conversao-peso
        image: lelebs/conversao-peso:v1
        ports:
          - containerPort: 80
---
# Service conversao-peso
apiVersion: v1
kind: Service
metadata:
  name: conversao-peso
spec:
  selector:
    app: conversao-peso
  ports:
    - port: 80
  type: NodePort